---
abstract: 'Organize Data in Tables'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  List::Util: 0
  Test::More: 0
  perl: 5.008
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
keywords:
  - art
  - ascii
  - asciiart
  - borders
  - table
  - text
  - unicode
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Table
provides:
  Text::Table:
    file: lib/Text/Table.pm
    version: 1.129
requires:
  Text::Aligner: 0.05
  strict: 0
  warnings: 0
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
  repository: https://github.com/shlomif/Text-Table
version: 1.129
